site_name: Personal Documentation
site_url: 
repo_url: 
theme:
  name: 'material'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  logo: assets/logo.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: light
      primary: 'light green'
      accent: 'blue'
      toggle:
        icon: material/toggle-switch-off-outline
        name: Embrace the dark side
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: 'blue grey'
      accent: 'amber'
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
# extra:
#   social:
#     - icon: 'fontawesome/brands/github'
#       link: 'https://github.com/selfhostedshow'
#     - icon: 'fontawesome/brands/twitter'
#       link: 'https://twitter.com/selfhostedshow'
#     - icon: 'fontawesome/solid/fire'
#       link: 'https://selfhosted.show/'
#     - icon: 'fontawesome/solid/graduation-cap'
#       link: 'https://linuxacademy.com'
#     - icon: 'fontawesome/brands/linux'
#       link: 'https://jupiterbroadcasting.com'
#     - icon: 'fontawesome/brands/discord'
#       link: 'https://discord.gg/n49fgkp'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - footnotes
  - mdx_include:
      base_path: docs
  - attr_list

plugins:
  - search
  - minify:
      minify_html: true
  - glightbox

extra_css:
  - stylesheets/extra.css
